### ISSUE TITLE
Watson v2.0 - Unhandled Exception Key not present

### ISSUE THREAD

**Issue by gr33nkiddy** [rasta-mouse/Watson#19]
Hi 

Today I followed htb walkthrough https://0xdf.gitlab.io/2019/03/05/htb-devel.html

Compiled the code as Net Framework v3.5 and ran the exe on the target machine. Following error showed. Any help? Thanks.

![image](https://user-images.githubusercontent.com/74125027/98457448-50543500-21c2-11eb-818d-170782b9e690.png)

**Comment by gr33nkiddy** [comment]
My bad. apologies. This is resolved.

**Comment by sidahmed-malaoui** [comment]
I'm still having a similar issue : 

![image](https://user-images.githubusercontent.com/19175347/101003313-88039200-3560-11eb-945b-ff71246036cb.png)

I built it using Visual Studio Community 2019 in Windows 7 (I don't know if this relevant or not)

**Comment by rasta-mouse** [comment]
@sidahmed-malaoui pull #20 and see if that fixes it for you.

**Comment by sidahmed-malaoui** [comment]
@rasta-mouse  I pulled and compiled it again. The error is gone, but now it says windows version not supported :

![image](https://user-images.githubusercontent.com/19175347/101012829-acad3900-3563-11eb-8f89-03d2b5442fe4.png)

It doesn't work in windows 7 ? or am I missing a dependency ?

(I'm sorry for asking a questions that might seem stupid, I'm a noob when it comes to windows stuff).

**Comment by rasta-mouse** [comment]
It doesn't support Windows 7, only 10, 2k16 and 2k19.

**Comment by sidahmed-malaoui** [comment]
@rasta-mouse Okay. thank you dude.
